import React, { useState } from 'react';
import { toast } from 'react-hot-toast';
import {
  ArrowDownTrayIcon,
  DocumentDuplicateIcon,
  FolderArrowDownIcon,
  PhotoIcon,
  DocumentTextIcon,
  ArrowPathIcon
} from '@heroicons/react/24/outline';
import JSZip from 'jszip';
import { apiService } from '../../services/api';

interface CopyVariant {
  headline: string;
  primaryText: string;
  description?: string;
  hashtags?: string[];
  approach?: string;
}

interface AdExportPanelProps {
  adId: string;
  copyVariants: CopyVariant[];
  visualAssets: Record<string, Record<string, any>>;
  videoAssets?: Record<string, any>;
  platforms: string[];
  callToAction: string;
  productName: string;
}

const AdExportPanel: React.FC<AdExportPanelProps> = ({
  adId,
  copyVariants,
  visualAssets,
  videoAssets,
  platforms,
  callToAction,
  productName
}) => {
  const [exporting, setExporting] = useState(false);
  const [exportProgress, setExportProgress] = useState(0);

  // Download image - handles both local and external URLs
  const downloadImage = async (url: string): Promise<Blob | null> => {
    try {
      // Check if it's a local URL (already on our server)
      const isLocalUrl = url.startsWith('/uploads/') || 
                         url.startsWith('./uploads/') || 
                         url.includes('/uploads/smart-ads/');
      
      if (isLocalUrl) {
        // For local URLs, fetch directly (same origin, no CORS issues)
        const fullUrl = url.startsWith('http') ? url : `${window.location.origin}${url}`;
        const response = await fetch(fullUrl);
        if (!response.ok) throw new Error('Failed to fetch local image');
        return await response.blob();
      }

      // For external URLs, try backend proxy first (avoids CORS)
      try {
        const proxyResponse = await apiService.post('/proxy/image', { url }) as any;
        if (proxyResponse.success && proxyResponse.data) {
          // Convert base64 to blob
          const byteCharacters = atob(proxyResponse.data);
          const byteNumbers = new Array(byteCharacters.length);
          for (let i = 0; i < byteCharacters.length; i++) {
            byteNumbers[i] = byteCharacters.charCodeAt(i);
          }
          const byteArray = new Uint8Array(byteNumbers);
          return new Blob([byteArray], { type: proxyResponse.contentType || 'image/png' });
        }
      } catch (proxyError) {
        console.log('Proxy fetch failed, trying direct fetch:', proxyError);
      }

      // Fallback to direct fetch (may fail due to CORS for external URLs)
      const response = await fetch(url);
      if (!response.ok) throw new Error('Failed to fetch image');
      return await response.blob();
    } catch (error) {
      console.error('Error downloading image:', error);
      return null;
    }
  };

  const handleExportAll = async () => {
    setExporting(true);
    setExportProgress(0);

    try {
      const zip = new JSZip();
      let totalItems = 0;
      let processedItems = 0;
      const failedImages: string[] = [];

      // Count total items
      platforms.forEach(platform => {
        if (visualAssets[platform]) {
          totalItems += Object.keys(visualAssets[platform]).length;
        }
      });
      totalItems += copyVariants.length; // For copy text files

      // Create folders for each platform
      for (const platform of platforms) {
        const platformFolder = zip.folder(platform);
        if (!platformFolder) continue;

        // Add images
        if (visualAssets[platform]) {
          const imagesFolder = platformFolder.folder('images');
          for (const [format, asset] of Object.entries(visualAssets[platform]) as [string, any][]) {
            if (asset.imageUrl && !asset.error) {
              const imageBlob = await downloadImage(asset.imageUrl);
              if (imageBlob) {
                const extension = asset.imageUrl.includes('.png') ? 'png' : 'jpg';
                imagesFolder?.file(`${format}_${asset.aspectRatio?.replace(':', 'x') || '1x1'}.${extension}`, imageBlob);
              } else {
                failedImages.push(`${platform}/${format}: ${asset.imageUrl}`);
              }
            }
            processedItems++;
            setExportProgress(Math.round((processedItems / totalItems) * 80));
          }
        }

        // Add copy variants
        const copyFolder = platformFolder.folder('copy');
        copyVariants.forEach((variant, index) => {
          const copyContent = `# Ad Copy Variant ${index + 1}

## Headline
${variant.headline}

## Primary Text
${variant.primaryText}

${variant.description ? `## Description\n${variant.description}\n` : ''}
## Hashtags
${variant.hashtags?.map((h: string) => `#${h}`).join(' ') || 'None'}

## Call to Action
${callToAction}

---
Generated by Ajentrix Smart Ad Generator
Product: ${productName}
Platform: ${platform}
`;
          copyFolder?.file(`variant_${index + 1}.md`, copyContent);
        });
      }

      // Add summary file with image URLs (useful if some images failed)
      let imageUrlList = '';
      platforms.forEach(platform => {
        if (visualAssets[platform]) {
          imageUrlList += `\n### ${platform.toUpperCase()}\n`;
          Object.entries(visualAssets[platform]).forEach(([format, asset]: [string, any]) => {
            if (asset.imageUrl && !asset.error) {
              imageUrlList += `- ${format} (${asset.aspectRatio || 'N/A'}): ${asset.imageUrl}\n`;
            }
          });
        }
      });

      const summary = `# Smart Ad Export Summary

## Product
${productName}

## Platforms
${platforms.join(', ')}

## Number of Variants
${copyVariants.length}

## Call to Action
${callToAction}

## Export Date
${new Date().toISOString()}

## Image URLs
${imageUrlList}
${failedImages.length > 0 ? `\n## Failed Downloads (use URLs above to download manually)\n${failedImages.map(f => `- ${f}`).join('\n')}` : ''}

---
Generated by Ajentrix Smart Ad Generator
`;
      zip.file('README.md', summary);

      setExportProgress(90);

      // Generate zip file
      const content = await zip.generateAsync({ type: 'blob' });
      
      setExportProgress(100);
      
      // Download
      const url = URL.createObjectURL(content);
      const link = document.createElement('a');
      link.href = url;
      link.download = `smart-ad-${adId.slice(0, 8)}-${productName.toLowerCase().replace(/\s+/g, '-')}.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      if (failedImages.length > 0) {
        toast.success(`Package downloaded! ${failedImages.length} image(s) couldn't be included - see README for URLs.`);
      } else {
        toast.success('Ad creative package downloaded!');
      }
    } catch (error) {
      console.error('Export failed:', error);
      toast.error('Failed to export ads. Please try again.');
    } finally {
      setExporting(false);
      setExportProgress(0);
    }
  };

  const handleCopyAllText = () => {
    const allCopy = copyVariants.map((variant, index) => 
      `=== Variant ${index + 1} ===\n\nHeadline: ${variant.headline}\n\nText: ${variant.primaryText}\n\nHashtags: ${variant.hashtags?.map(h => `#${h}`).join(' ') || ''}`
    ).join('\n\n---\n\n');
    
    navigator.clipboard.writeText(allCopy);
    toast.success('All copy variants copied to clipboard!');
  };

  const handleExportCSV = () => {
    const headers = ['Variant', 'Headline', 'Primary Text', 'Description', 'Hashtags', 'CTA', 'Platforms'];
    const rows = copyVariants.map((variant, index) => [
      index + 1,
      `"${variant.headline.replace(/"/g, '""')}"`,
      `"${variant.primaryText.replace(/"/g, '""')}"`,
      `"${(variant.description || '').replace(/"/g, '""')}"`,
      `"${variant.hashtags?.join(', ') || ''}"`,
      callToAction,
      platforms.join(', ')
    ]);

    const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `ad-copy-${productName.toLowerCase().replace(/\s+/g, '-')}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast.success('CSV exported successfully!');
  };

  const handleExportJSON = () => {
    const exportData = {
      productName,
      platforms,
      callToAction,
      copyVariants,
      visualAssets,
      videoAssets,
      exportedAt: new Date().toISOString()
    };

    const json = JSON.stringify(exportData, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `smart-ad-${adId.slice(0, 8)}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast.success('JSON exported successfully!');
  };

  return (
    <div className="bg-slate-800/50 backdrop-blur rounded-2xl p-6 border border-slate-700/50">
      <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
        <FolderArrowDownIcon className="h-5 w-5 text-green-400" />
        Export & Download
      </h3>

      <div className="space-y-3">
        {/* Download All */}
        <button
          onClick={handleExportAll}
          disabled={exporting}
          className="w-full flex items-center justify-between px-4 py-3 bg-gradient-to-r from-green-600 to-emerald-600 rounded-xl text-white font-medium hover:from-green-500 hover:to-emerald-500 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
        >
          <div className="flex items-center gap-3">
            {exporting ? (
              <ArrowPathIcon className="h-5 w-5 animate-spin" />
            ) : (
              <ArrowDownTrayIcon className="h-5 w-5" />
            )}
            <div className="text-left">
              <p className="font-semibold">Download All Assets</p>
              <p className="text-xs text-green-200">ZIP with images, videos & copy</p>
            </div>
          </div>
          {exporting && (
            <span className="text-sm">{exportProgress}%</span>
          )}
        </button>

        {/* Export Options Grid */}
        <div className="grid grid-cols-2 gap-3">
          {/* Copy All Text */}
          <button
            onClick={handleCopyAllText}
            className="flex items-center gap-2 px-4 py-3 bg-slate-700/50 rounded-xl text-gray-300 hover:bg-slate-700 hover:text-white transition-all"
          >
            <DocumentDuplicateIcon className="h-5 w-5 text-blue-400" />
            <div className="text-left">
              <p className="font-medium text-sm">Copy All Text</p>
              <p className="text-xs text-gray-500">Clipboard</p>
            </div>
          </button>

          {/* Export CSV */}
          <button
            onClick={handleExportCSV}
            className="flex items-center gap-2 px-4 py-3 bg-slate-700/50 rounded-xl text-gray-300 hover:bg-slate-700 hover:text-white transition-all"
          >
            <DocumentTextIcon className="h-5 w-5 text-orange-400" />
            <div className="text-left">
              <p className="font-medium text-sm">Export CSV</p>
              <p className="text-xs text-gray-500">Spreadsheet</p>
            </div>
          </button>

          {/* Export JSON */}
          <button
            onClick={handleExportJSON}
            className="flex items-center gap-2 px-4 py-3 bg-slate-700/50 rounded-xl text-gray-300 hover:bg-slate-700 hover:text-white transition-all"
          >
            <DocumentTextIcon className="h-5 w-5 text-yellow-400" />
            <div className="text-left">
              <p className="font-medium text-sm">Export JSON</p>
              <p className="text-xs text-gray-500">API/Dev</p>
            </div>
          </button>

          {/* Images Only */}
          <button
            onClick={() => toast.success('Coming soon!')}
            className="flex items-center gap-2 px-4 py-3 bg-slate-700/50 rounded-xl text-gray-300 hover:bg-slate-700 hover:text-white transition-all"
          >
            <PhotoIcon className="h-5 w-5 text-purple-400" />
            <div className="text-left">
              <p className="font-medium text-sm">Images Only</p>
              <p className="text-xs text-gray-500">PNG files</p>
            </div>
          </button>
        </div>

        {/* Platform-specific exports */}
        <div className="mt-4 pt-4 border-t border-slate-700">
          <p className="text-sm text-gray-400 mb-3">Export for specific platform:</p>
          <div className="flex flex-wrap gap-2">
            {platforms.map(platform => (
              <button
                key={platform}
                onClick={() => toast.success(`${platform} export coming soon!`)}
                className="px-3 py-1.5 bg-slate-700/30 rounded-lg text-sm text-gray-400 hover:bg-slate-700 hover:text-white transition-all capitalize"
              >
                {platform}
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdExportPanel;

