-- Add writing style learning to ai_agents
-- When enabled, content generated by the agent will match the user's writing samples (vocabulary, tone, structure).

ALTER TABLE ai_agents
ADD COLUMN IF NOT EXISTS writing_style_enabled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS writing_style_samples JSONB DEFAULT '[]';

COMMENT ON COLUMN ai_agents.writing_style_enabled IS 'When true, generated content should mimic the writing samples';
COMMENT ON COLUMN ai_agents.writing_style_samples IS 'Array of text strings: user writing samples used to learn style';
