-- Migration: Add AI generation fields to ebook_projects table
-- This allows users to specify chapter count, word count, and auto-generation options

-- Add new columns for AI generation options
ALTER TABLE ebook_projects 
  ADD COLUMN IF NOT EXISTS number_of_chapters INTEGER,
  ADD COLUMN IF NOT EXISTS target_word_count INTEGER,
  ADD COLUMN IF NOT EXISTS word_count_type VARCHAR(20) DEFAULT 'per_chapter', -- 'total' or 'per_chapter'
  ADD COLUMN IF NOT EXISTS writing_style VARCHAR(50),
  ADD COLUMN IF NOT EXISTS auto_generate_chapters BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS chapter_outline JSONB,
  ADD COLUMN IF NOT EXISTS generation_status VARCHAR(20) DEFAULT 'not_started'; -- 'not_started', 'generating', 'completed', 'failed'

-- Add index for generation status
CREATE INDEX IF NOT EXISTS idx_ebook_projects_generation_status ON ebook_projects(generation_status);

-- Add comment for documentation
COMMENT ON COLUMN ebook_projects.number_of_chapters IS 'Target number of chapters for the eBook';
COMMENT ON COLUMN ebook_projects.target_word_count IS 'Target word count (total or per chapter based on word_count_type)';
COMMENT ON COLUMN ebook_projects.word_count_type IS 'Type of word count: total (for entire book) or per_chapter';
COMMENT ON COLUMN ebook_projects.writing_style IS 'Writing style preference (professional, casual, academic, creative, etc.)';
COMMENT ON COLUMN ebook_projects.auto_generate_chapters IS 'Whether to auto-generate chapters on project creation';
COMMENT ON COLUMN ebook_projects.chapter_outline IS 'JSON array of chapter titles and descriptions generated by AI';
COMMENT ON COLUMN ebook_projects.generation_status IS 'Status of chapter generation process';

