-- Create generated_lyrics table to store standalone lyrics generation
CREATE TABLE IF NOT EXISTS generated_lyrics (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    agent_id UUID REFERENCES ai_agents(id) ON DELETE SET NULL,
    
    -- Generation parameters
    topic VARCHAR(500),
    genre VARCHAR(100),
    mood VARCHAR(50) NOT NULL DEFAULT 'energetic',
    style VARCHAR(50) NOT NULL DEFAULT 'pop',
    language VARCHAR(10) NOT NULL DEFAULT 'en',
    length VARCHAR(20) NOT NULL DEFAULT 'medium', -- 'short', 'medium', 'long'
    structure VARCHAR(50) NOT NULL DEFAULT 'auto', -- 'auto', 'verse-chorus', 'verse-only', 'free-form'
    
    -- Generated content
    title VARCHAR(500),
    lyrics_text TEXT NOT NULL,
    line_count VARCHAR(50),
    reasoning TEXT,
    
    -- Metadata
    metadata JSONB DEFAULT '{}',
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_generated_lyrics_user_id ON generated_lyrics(user_id);
CREATE INDEX IF NOT EXISTS idx_generated_lyrics_agent_id ON generated_lyrics(agent_id);
CREATE INDEX IF NOT EXISTS idx_generated_lyrics_created_at ON generated_lyrics(created_at DESC);

-- Add comment
COMMENT ON TABLE generated_lyrics IS 'Stores standalone lyrics generated by AI, separate from music generation';

