-- Content Briefs Migration
-- Table for storing content briefs generated by the Content Brief Generator

CREATE TABLE IF NOT EXISTS content_briefs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  agent_id UUID REFERENCES ai_agents(id) ON DELETE SET NULL,
  topic TEXT NOT NULL,
  platform VARCHAR(50),
  content_type VARCHAR(50),
  brief_data JSONB NOT NULL,
  completeness_score INTEGER,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_content_briefs_user ON content_briefs(user_id);
CREATE INDEX IF NOT EXISTS idx_content_briefs_agent ON content_briefs(agent_id);
CREATE INDEX IF NOT EXISTS idx_content_briefs_created ON content_briefs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_briefs_platform ON content_briefs(platform);

