import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Agent, PlatformConnection } from '../types';
import { apiService } from '../services/api';
import { imageService } from '../services/imageService';
import AgentEngagementDashboard from '../components/Agents/AgentEngagementDashboard';
import TelegramPostModal from '../components/Telegram/TelegramPostModal';
import TelegramEngagementSettings from '../components/Telegram/TelegramEngagementSettings';
import AgentPlatformSettings from '../components/Agents/AgentPlatformSettings';
import MusicGallery from '../components/Music/MusicGallery';
import toast from 'react-hot-toast';
import { Music, Loader2 } from 'lucide-react';
import { resolveImageUrl } from '@/utils/domain';
import { agentProfilePath } from '@/utils/slug';

const AgentDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [agent, setAgent] = useState<Agent | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [editForm, setEditForm] = useState({
    name: '',
    description: '',
    is_active: false,
    preferred_voice_type: '',
    preferred_music_language: ''
  });
  const [activeTab, setActiveTab] = useState('overview'); // Added state for active tab
  const [isTelegramModalOpen, setIsTelegramModalOpen] = useState(false);
  const [isEngagementSettingsOpen, setIsEngagementSettingsOpen] = useState(false);
  const [isGeneratingMusic, setIsGeneratingMusic] = useState(false);
  const [showMusicModal, setShowMusicModal] = useState(false);
  const [writingSamplesText, setWritingSamplesText] = useState('');
  const [savingWritingStyle, setSavingWritingStyle] = useState(false);

  useEffect(() => {
    if (id) {
      fetchAgentDetails();
    }
  }, [id]);

  useEffect(() => {
    if (agent?.writing_style_samples?.length) {
      setWritingSamplesText(agent.writing_style_samples.join('\n\n---\n\n'));
    } else {
      setWritingSamplesText('');
    }
  }, [agent?.id, agent?.writing_style_samples]);

  const fetchAgentDetails = async () => {
    try {
      setLoading(true);
      const response = await apiService.get(`/agents/${id}`);
      
      // Check if the response has the expected structure
      if (response.success && response.data) {
        setAgent(response.data);
        setEditForm({
          name: response.data.name,
          description: response.data.description,
          is_active: response.data.status === 'active',
          preferred_voice_type: response.data.preferred_voice_type || '',
          preferred_music_language: response.data.preferred_music_language || ''
        });
      } else {
        throw new Error('Invalid response format from server');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async () => {
    try {
      await apiService.put(`/agents/${id}`, editForm);
      await fetchAgentDetails();
      setIsEditing(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to update agent');
    }
  };

  const toggleAgentStatus = async () => {
    try {
      const newStatus = !editForm.is_active;
      await apiService.post(`/agents/${id}/toggle-status`, { is_active: newStatus });
      setEditForm(prev => ({ ...prev, is_active: newStatus }));
      if (agent) {
        setAgent(prev => prev ? { ...prev, status: newStatus ? 'active' : 'inactive' } : null);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to toggle status');
    }
  };

  const deleteAgent = async () => {
    if (!confirm('Are you sure you want to delete this agent? This action cannot be undone.')) {
      return;
    }

    try {
      await apiService.delete(`/agents/${id}`);
      navigate('/agents');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete agent');
    }
  };

  const handleGenerateMusic = async () => {
    if (!id) return;
    
    setIsGeneratingMusic(true);
    try {
      const response = await imageService.generateMusicWithAgent(id, {
        duration: 30,
        instrumental: false
      });

      if (response.success && response.data) {
        toast.success(`Music generated by ${agent?.name}! ${response.data.status === 'processing' ? 'It will be ready shortly.' : ''}`);
        setShowMusicModal(true);
      } else {
        throw new Error(response.error || 'Failed to generate music');
      }
    } catch (err: any) {
      console.error('Music generation error:', err);
      const errorMessage = err.response?.data?.details || err.message || 'Failed to generate music';
      const suggestions = err.response?.data?.suggestions;
      
      toast.error(errorMessage);
      if (suggestions && suggestions.length > 0) {
        console.log('Suggestions:', suggestions);
      }
    } finally {
      setIsGeneratingMusic(false);
    }
  };

  if (loading) {
    return (
      <div className="p-6 flex items-center justify-center">
        <div className="text-white">Loading agent details...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-6">
        <div className="glass-card p-6 text-center">
          <div className="text-red-400 mb-4">Error: {error}</div>
          <button 
            onClick={() => fetchAgentDetails()}
            className="btn-primary"
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  if (!agent) {
    return (
      <div className="p-6">
        <div className="glass-card p-6 text-center">
          <div className="text-red-400 mb-4">Agent not found</div>
          <button 
            onClick={() => navigate('/agents')}
            className="btn-primary"
          >
            Back to Agents
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
      <div>
          <h1 className="text-3xl font-bold text-white">{agent.name}</h1>
        <p className="text-gray-400 mt-1">
            {agent.description || 'No description provided'}
          </p>
        </div>
        <div className="flex space-x-3">
          <button
            onClick={() => setIsEditing(!isEditing)}
            className="btn-secondary"
          >
            {isEditing ? 'Cancel' : 'Edit'}
          </button>
          {isEditing && (
            <button
              onClick={handleSave}
              className="btn-primary"
            >
              Save Changes
            </button>
          )}
        </div>
      </div>

      {/* Agent Avatar */}
      <div className="glass-card p-6">
        <div className="flex items-center space-x-6">
          <div className="h-24 w-24 bg-gradient-to-br from-purple-500 to-pink-500 rounded-xl flex items-center justify-center overflow-hidden">
            {agent.avatar_url ? (
              <>
                <img 
                  src={resolveImageUrl(agent.avatar_url) || ''} 
                  alt={`${agent.name} avatar`}
                  className="w-full h-full object-cover"
                  onError={(e) => {
                    const target = e.target as HTMLImageElement;
                    target.style.display = 'none';
                    target.nextElementSibling?.classList.remove('hidden');
                  }}
                />
                <span className="text-white font-semibold text-3xl hidden">
                  {agent.name.charAt(0)}
                </span>
              </>
            ) : (
              <span className="text-white font-semibold text-3xl">
                {agent.name.charAt(0)}
              </span>
            )}
          </div>
          <div className="flex-1">
            <h3 className="text-lg font-semibold text-white mb-2">Agent Avatar</h3>
            <p className="text-gray-400 text-sm">
              {agent.avatar_url ? 'AI-generated or custom uploaded avatar' : 'No avatar set'}
            </p>
            {agent.avatar_url && (
              <div className="mt-2">
                <a 
                  href={resolveImageUrl(agent.avatar_url) || '#'} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-blue-400 hover:text-blue-300 text-sm"
                >
                  View Full Size →
                </a>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Status Badge */}
      <div className="flex items-center space-x-4">
        <span className={`px-3 py-1 rounded-full text-sm font-medium ${
          agent.status === 'active' 
            ? 'bg-green-500/20 text-green-400 border border-green-500/30' 
            : 'bg-red-500/20 text-red-400 border border-red-500/30'
        }`}>
          {agent.status === 'active' ? 'Active' : 'Inactive'}
        </span>
        <button
          onClick={toggleAgentStatus}
          className={`px-3 py-1 rounded-full text-sm font-medium transition-colors ${
            editForm.is_active
              ? 'bg-red-500/20 text-red-400 border border-red-500/30 hover:bg-red-500/30'
              : 'bg-green-500/20 text-green-400 border border-green-500/30 hover:bg-green-500/30'
          }`}
        >
          {editForm.is_active ? 'Deactivate' : 'Activate'}
        </button>
      </div>

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column - Agent Info */}
        <div className="lg:col-span-2 space-y-6">
          {/* Basic Information */}
          <div className="glass-card p-6">
            <h2 className="text-xl font-semibold text-white mb-4">Basic Information</h2>
            {isEditing ? (
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    Agent Name
                  </label>
                  <input
                    type="text"
                    value={editForm.name}
                    onChange={(e) => setEditForm(prev => ({ ...prev, name: e.target.value }))}
                    className="w-full px-3 py-2 bg-gray-800 border border-gray-600 rounded-md text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    Description
                  </label>
                  <textarea
                    value={editForm.description}
                    onChange={(e) => setEditForm(prev => ({ ...prev, description: e.target.value }))}
                    rows={3}
                    className="w-full px-3 py-2 bg-gray-800 border border-gray-600 rounded-md text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>

                {/* Music Generation Preferences */}
                <div className="border-t border-gray-700 pt-4 mt-4">
                  <h3 className="text-md font-semibold text-white mb-3">Music Generation Preferences</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">
                        Preferred Voice Type
                      </label>
                      <select
                        value={editForm.preferred_voice_type || ''}
                        onChange={(e) => setEditForm(prev => ({ ...prev, preferred_voice_type: e.target.value }))}
                        className="w-full px-3 py-2 bg-gray-800 border border-gray-600 rounded-md text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                      >
                        <option value="">Use Company Default</option>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                        <option value="neutral">Neutral</option>
                        <option value="auto">Auto (Let AI Decide)</option>
                        <option value="tenor">Tenor</option>
                        <option value="alto">Alto</option>
                        <option value="bass">Bass</option>
                        <option value="soprano">Soprano</option>
                      </select>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">
                        Preferred Music Language
                      </label>
                      <select
                        value={editForm.preferred_music_language || ''}
                        onChange={(e) => setEditForm(prev => ({ ...prev, preferred_music_language: e.target.value }))}
                        className="w-full px-3 py-2 bg-gray-800 border border-gray-600 rounded-md text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
                      >
                        <option value="">Use Company Default</option>
                        <option value="en">English</option>
                        <option value="es">Spanish</option>
                        <option value="fr">French</option>
                        <option value="de">German</option>
                        <option value="it">Italian</option>
                        <option value="pt">Portuguese</option>
                        <option value="ja">Japanese</option>
                        <option value="ko">Korean</option>
                        <option value="zh">Chinese</option>
                        <option value="ru">Russian</option>
                        <option value="ar">Arabic</option>
                        <option value="hi">Hindi</option>
                      </select>
                    </div>
                  </div>
                  <p className="text-xs text-gray-500 mt-2">
                    These settings will be used for all music generated by this agent. Leave empty to use company profile defaults.
                  </p>
                </div>
              </div>
            ) : (
              <div className="space-y-3">
                <div>
                  <span className="text-gray-400">Name:</span>
                  <span className="text-white ml-2">{agent.name}</span>
                </div>
                <div>
                  <span className="text-gray-400">Description:</span>
                  <span className="text-white ml-2">{agent.description || 'No description'}</span>
                </div>
                <div>
                  <span className="text-gray-400">Created:</span>
                  <span className="text-white ml-2">
                    {new Date(agent.created_at).toLocaleDateString()}
                  </span>
                </div>
                <div>
                  <span className="text-gray-400">Last Updated:</span>
                  <span className="text-white ml-2">
                    {new Date(agent.updated_at).toLocaleDateString()}
                  </span>
                </div>
              </div>
            )}
          </div>

          {/* Tab Navigation */}
          <div className="glass-card p-6">
            <div className="border-b border-gray-700 mb-6">
              <nav className="-mb-px flex space-x-8">
                {[
                  { id: 'overview', name: 'Overview', icon: '📊' },
                  { id: 'engagement', name: 'Engagement', icon: '💬' },
                  { id: 'music', name: 'Music', icon: '🎵' },
                  { id: 'analytics', name: 'Analytics', icon: '📈' },
                  { id: 'settings', name: 'Settings', icon: '⚙️' }
                ].map((tab) => (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id as any)}
                    className={`py-2 px-1 border-b-2 font-medium text-sm flex items-center gap-2 transition-colors ${
                      activeTab === tab.id
                        ? 'border-purple-500 text-purple-400'
                        : 'border-transparent text-gray-400 hover:text-gray-300 hover:border-gray-600'
                    }`}
                  >
                    <span>{tab.icon}</span>
                    {tab.name}
                  </button>
                ))}
              </nav>
            </div>

            {/* Tab Content */}
            {activeTab === 'overview' && (
              <div className="space-y-6">
                {/* Personality Configuration */}
                <div>
                  <h3 className="text-lg font-semibold text-white mb-4">Personality Configuration</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <span className="text-gray-400">Core Traits:</span>
                      <div className="flex flex-wrap gap-2 mt-2">
                        {agent.personality_config?.core_traits?.map((trait, index) => (
                          <span key={index} className="px-2 py-1 bg-blue-500/20 text-blue-400 rounded-md text-sm">
                            {trait}
                          </span>
                        )) || <span className="text-gray-500">No traits defined</span>}
                      </div>
                    </div>
                    <div>
                      <span className="text-gray-400">Communication Style:</span>
                      <span className="text-white ml-2 capitalize">
                        {agent.personality_config?.communication_style || 'Not specified'}
                      </span>
                    </div>
                    <div>
                      <span className="text-gray-400">Expertise Areas:</span>
                      <div className="flex flex-wrap gap-2 mt-2">
                        {agent.personality_config?.expertise_areas?.map((area, index) => (
                          <span key={index} className="px-2 py-1 bg-green-500/20 text-green-400 rounded-md text-sm">
                            {area}
                          </span>
                        )) || <span className="text-gray-500">No areas defined</span>}
                      </div>
                    </div>
                    <div>
                      <span className="text-gray-400">Response Tone:</span>
                      <span className="text-white ml-2 capitalize">
                        {agent.personality_config?.response_tone || 'Not specified'}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Performance Metrics */}
                <div>
                  <h3 className="text-lg font-semibold text-white mb-4">Performance Metrics</h3>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <div className="text-center">
                      <div className="text-2xl font-bold text-blue-400">
                        {agent.performance_metrics?.total_interactions || 0}
                      </div>
                      <div className="text-gray-400 text-sm">Total Interactions</div>
                    </div>
                    <div className="text-center">
                      <div className="text-2xl font-bold text-green-400">
                        {agent.performance_metrics?.engagement_rate || 0}%
                      </div>
                      <div className="text-gray-400 text-sm">Engagement Rate</div>
                    </div>
                    <div className="text-center">
                      <div className="text-2xl font-bold text-yellow-400">
                        {agent.performance_metrics?.response_time_avg || 0}s
                      </div>
                      <div className="text-gray-400 text-sm">Avg Response Time</div>
                    </div>
                    <div className="text-center">
                      <div className="text-2xl font-bold text-purple-400">
                        {agent.performance_metrics?.satisfaction_score || 0}/5
                      </div>
                      <div className="text-gray-400 text-sm">Satisfaction Score</div>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {activeTab === 'engagement' && (
              <div>
                <h3 className="text-lg font-semibold text-white mb-4">Engagement Dashboard</h3>
                <AgentEngagementDashboard agentId={agent.id} agentName={agent.name} />
              </div>
            )}

            {activeTab === 'music' && (
              <div>
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-white">Generated Music</h3>
                  <button
                    onClick={handleGenerateMusic}
                    disabled={isGeneratingMusic}
                    className="btn-primary flex items-center space-x-2"
                  >
                    {isGeneratingMusic ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        <span>Generating...</span>
                      </>
                    ) : (
                      <>
                        <Music className="w-4 h-4" />
                        <span>Generate Music</span>
                      </>
                    )}
                  </button>
                </div>
                <p className="text-gray-400 text-sm mb-4">
                  Music generated by {agent?.name} based on their personality and style. Each track is uniquely created to match the agent's voice and characteristics.
                </p>
                <MusicGallery agentId={agent?.id} />
              </div>
            )}

            {activeTab === 'analytics' && (
              <div>
                <h3 className="text-lg font-semibold text-white mb-4">Analytics Dashboard</h3>
                <div className="text-center py-12">
                  <div className="text-gray-400 mb-4">📊</div>
                  <div className="text-gray-400 mb-2">Analytics Dashboard</div>
                  <div className="text-gray-500 text-sm">Detailed performance analytics coming soon</div>
                </div>
              </div>
            )}

            {activeTab === 'settings' && (
              <div>
                <h3 className="text-lg font-semibold text-white mb-4">Agent Settings</h3>
                <div className="space-y-6">
                  {/* Platform Settings */}
                  <AgentPlatformSettings 
                    agentId={agent.id}
                    currentPlatforms={agent.platforms || []}
                    onUpdate={fetchAgentDetails}
                  />

                  {/* Forum Settings */}
                  <div className="bg-gray-800 rounded-xl p-6 border border-gray-700">
                    <h4 className="text-white font-semibold mb-4 flex items-center gap-2">
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z" />
                      </svg>
                      Agent Forum Settings
                    </h4>
                    
                    <div className="space-y-4">
                      {/* Image Posting Toggle */}
                      <div className="flex items-center justify-between">
                        <div>
                          <label className="text-white font-medium">Allow Image Posting in Forums</label>
                          <p className="text-sm text-gray-400 mt-1">
                            When enabled, this agent can include images in forum posts
                          </p>
                        </div>
                        <label className="relative inline-flex items-center cursor-pointer">
                          <input
                            type="checkbox"
                            checked={agent.can_post_forum_images ?? false}
                            onChange={async (e) => {
                              try {
                                await apiService.put(`/agents/${agent.id}`, {
                                  can_post_forum_images: e.target.checked
                                });
                                toast.success('Forum image setting updated');
                                fetchAgentDetails();
                              } catch (err) {
                                toast.error('Failed to update setting');
                              }
                            }}
                            className="sr-only peer"
                          />
                          <div className="w-11 h-6 bg-gray-700 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-800 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
                        </label>
                      </div>

                      {/* Profile Header Upload */}
                      <div>
                        <label className="text-white font-medium block mb-2">Profile Header Image</label>
                        <p className="text-sm text-gray-400 mb-3">
                          Upload a custom header image for the agent's profile page (recommended: 1500x500px)
                        </p>
                        {agent.profile_header_image && (
                          <div className="mb-3">
                            <img 
                              src={resolveImageUrl(agent.profile_header_image) || ''} 
                              alt="Profile header" 
                              className="w-full h-32 object-cover rounded-lg border border-gray-600"
                            />
                          </div>
                        )}
                        <div className="flex gap-2">
                          <input
                            type="file"
                            accept="image/*"
                            id="header-image-upload"
                            onChange={async (e) => {
                              const file = e.target.files?.[0];
                              if (!file) return;
                              
                              // Validate file type
                              if (!file.type.startsWith('image/')) {
                                toast.error('Please select an image file');
                                return;
                              }
                              
                              // Validate file size (10MB for header images)
                              if (file.size > 10 * 1024 * 1024) {
                                toast.error('Image must be less than 10MB');
                                return;
                              }
                              
                              const formData = new FormData();
                              formData.append('image', file);
                              
                              const toastId = toast.loading('Uploading header image...');
                              
                              try {
                                const response = await apiService.post<{ imageUrl: string }>('/agents/upload-header-image', formData);
                                
                                if (response.success && response.data?.imageUrl) {
                                  await apiService.put(`/agents/${agent.id}`, {
                                    profile_header_image: response.data.imageUrl
                                  });
                                  toast.success('Profile header updated!', { id: toastId });
                                  fetchAgentDetails();
                                  // Clear the input
                                  e.target.value = '';
                                } else {
                                  toast.error('Upload failed', { id: toastId });
                                }
                              } catch (err: any) {
                                console.error('Upload error:', err);
                                toast.error(err?.response?.data?.error || 'Failed to upload header image', { id: toastId });
                              }
                            }}
                            className="block w-full text-sm text-gray-400 file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 file:text-sm file:font-semibold file:bg-blue-600 file:text-white hover:file:bg-blue-700 file:cursor-pointer"
                          />
                          {agent.profile_header_image && (
                            <button
                              onClick={async () => {
                                try {
                                  await apiService.put(`/agents/${agent.id}`, {
                                    profile_header_image: null
                                  });
                                  toast.success('Header image removed');
                                  fetchAgentDetails();
                                } catch (err) {
                                  toast.error('Failed to remove header');
                                }
                              }}
                              className="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg text-sm whitespace-nowrap"
                            >
                              Remove
                            </button>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Writing style – learn user's style from samples */}
                  <div className="bg-gray-800 rounded-xl p-6 border border-gray-700">
                    <h4 className="text-white font-semibold mb-4 flex items-center gap-2">
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                      </svg>
                      Writing style
                    </h4>
                    <p className="text-sm text-gray-400 mb-4">
                      When enabled, content generated by this agent will match your vocabulary, tone, and sentence structure. Add 2–5 short writing samples (e.g. your posts or emails).
                    </p>
                    <div className="space-y-4">
                      <div className="flex items-center justify-between">
                        <label className="text-white font-medium">Use my writing style</label>
                        <label className="relative inline-flex items-center cursor-pointer">
                          <input
                            type="checkbox"
                            checked={agent.writing_style_enabled ?? false}
                            onChange={async (e) => {
                              try {
                                await apiService.put(`/agents/${agent.id}`, {
                                  writing_style_enabled: e.target.checked
                                });
                                toast.success(e.target.checked ? 'Writing style enabled' : 'Writing style disabled');
                                fetchAgentDetails();
                              } catch (err) {
                                toast.error('Failed to update setting');
                              }
                            }}
                            className="sr-only peer"
                          />
                          <div className="w-11 h-6 bg-gray-700 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-800 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
                        </label>
                      </div>
                      <div>
                        <label className="text-white font-medium block mb-2">Writing samples</label>
                        <p className="text-sm text-gray-400 mb-2">Separate each sample with a blank line or <code className="text-gray-500">---</code></p>
                        <textarea
                          value={writingSamplesText}
                          onChange={(e) => setWritingSamplesText(e.target.value)}
                          placeholder="Paste 2–5 samples of how you write (posts, emails, captions)..."
                          rows={6}
                          className="w-full px-4 py-3 bg-gray-700 border border-gray-600 rounded-lg text-white placeholder-gray-500 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        />
                        <button
                          type="button"
                          disabled={savingWritingStyle}
                          onClick={async () => {
                            const raw = writingSamplesText.trim();
                            const samples = raw ? raw.split(/\n *--- *\n|\n\n+/).map((s) => s.trim()).filter(Boolean) : [];
                            setSavingWritingStyle(true);
                            try {
                              await apiService.put(`/agents/${agent.id}`, {
                                writing_style_samples: samples
                              });
                              toast.success(samples.length ? `Saved ${samples.length} sample(s)` : 'Samples cleared');
                              fetchAgentDetails();
                            } catch (err) {
                              toast.error('Failed to save samples');
                            } finally {
                              setSavingWritingStyle(false);
                            }
                          }}
                          className="mt-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white rounded-lg text-sm"
                        >
                          {savingWritingStyle ? 'Saving...' : 'Save samples'}
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>


        </div>

        {/* Right Column - Platform Connections & Actions */}
        <div className="space-y-6">
          {/* Platform Connections */}
          <div className="glass-card p-6">
            <h2 className="text-xl font-semibold text-white mb-4">Platform Connections</h2>
            {agent.platform_connections && agent.platform_connections.length > 0 ? (
              <div className="space-y-3">
                {agent.platform_connections.map((connection: any, index) => (
                  <div key={index} className="flex items-center justify-between p-3 bg-gray-800/50 rounded-lg">
                    <div className="flex items-center space-x-3">
                      <div className={`w-3 h-3 rounded-full ${
                        connection.status === 'active' ? 'bg-green-400' : 'bg-red-400'
                      }`} />
                      <span className="text-white capitalize">{connection.platform}</span>
                    </div>
                    <div className="text-right">
                      <span className={`text-sm ${
                        connection.status === 'active' ? 'text-green-400' : 'text-red-400'
                      }`}>
                        {connection.status === 'active' ? 'Connected' : 'Disconnected'}
                      </span>
                      {connection.username && (
                        <div className="text-xs text-gray-400">@{connection.username}</div>
                      )}
                      {connection.followers && (
                        <div className="text-xs text-gray-400">{connection.followers} followers</div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center py-4">
                <div className="text-gray-400 mb-2">No platforms connected</div>
                <button 
                  onClick={() => navigate('/settings')}
                  className="btn-primary text-sm"
                >
                  Connect Platform
                </button>
              </div>
            )}
          </div>

          {/* Quick Actions */}
          <div className="glass-card p-6">
            <h2 className="text-xl font-semibold text-white mb-4">Quick Actions</h2>
            <div className="space-y-3">
              <button 
                onClick={() => navigate(agentProfilePath(agent.name, agent.id))}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center justify-center"
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                </svg>
                View Agent Profile
              </button>
              <button 
                onClick={() => window.location.href = `/ai-content?agent=${agent.id}`}
                className="w-full btn-primary"
              >
                Generate Content
              </button>
              <button 
                onClick={() => {
                  console.log('Agent ID for widget:', agent.id);
                  if (agent.id) {
                    navigate(`/agents/${agent.id}/widget`);
                  } else {
                    console.error('Agent ID is undefined');
                  }
                }}
                className="w-full bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center justify-center"
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                </svg>
                Website Widget
              </button>
              <button 
                onClick={() => setIsTelegramModalOpen(true)}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center justify-center"
              >
                <svg className="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zm5.568 8.16l-1.61 7.59c-.12.56-.44.7-.89.44l-2.46-1.81-1.19 1.15c-.13.13-.24.24-.49.24l.18-2.56 4.57-4.13c.2-.18-.04-.28-.31-.1l-5.64 3.55-2.43-.76c-.53-.16-.54-.53.11-.79l9.46-3.65c.44-.16.83.1.69.79z"/>
                </svg>
                Post to Telegram
              </button>
              <button 
                onClick={() => setIsEngagementSettingsOpen(true)}
                className="w-full bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center justify-center"
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
                Telegram Engagement
              </button>
              <button 
                onClick={() => window.location.href = `/scheduled-posts?agent=${agent.id}`}
                className="w-full btn-secondary"
              >
                Schedule Posts
              </button>
              <button 
                onClick={() => handleGenerateMusic()}
                className="w-full bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center justify-center"
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zM9 10l12-3" />
                </svg>
                Generate Music
              </button>
              <button 
                onClick={() => navigate('/analytics')}
                className="w-full btn-secondary"
              >
                View Analytics
              </button>
            </div>
          </div>

          {/* Danger Zone */}
          <div className="glass-card p-6 border border-red-500/30">
            <h2 className="text-xl font-semibold text-red-400 mb-4">Danger Zone</h2>
            <button
              onClick={deleteAgent}
              className="w-full btn-danger"
            >
              Delete Agent
            </button>
            <p className="text-red-400 text-sm mt-2 text-center">
              This action cannot be undone
            </p>
          </div>
        </div>
      </div>

      {/* Telegram Post Modal */}
      <TelegramPostModal
        isOpen={isTelegramModalOpen}
        onClose={() => setIsTelegramModalOpen(false)}
        agentId={agent.id}
        agentName={agent.name}
        onSuccess={(result) => {
          console.log('Telegram post successful:', result);
          // Optionally refresh agent data or show success message
        }}
      />

      {/* Telegram Engagement Settings Modal */}
      {isEngagementSettingsOpen && (
        <TelegramEngagementSettings
          agentId={agent.id}
          agentName={agent.name}
          onClose={() => setIsEngagementSettingsOpen(false)}
        />
      )}
    </div>
  );
};

export default AgentDetail; 